SELECT SUM(soluong) FROM NGUOIHIENMAU JOIN LICHSUHIENMAU ON NGUOIHIENMAU.manguoi = LICHSUHIENMAU.manguoi JOIN DOTHIENMAU ON LICHSUHIENMAU.madot = DOTHIENMAU.madot 
WHERE mamau = 2 AND (DOTHIENMAU.madot IN (SELECT madot FROM DOTHIENMAU where YEAR(ngaybatdau) = 2017 and MONTH(ngaybatdau) = 1) OR DOTHIENMAU.madot = 1)



SELECT SUM(soluong) FROM NGUOIHIENMAU JOIN LICHSUHIENMAU ON NGUOIHIENMAU.manguoi = LICHSUHIENMAU.manguoi JOIN DOTHIENMAU ON LICHSUHIENMAU.madot = DOTHIENMAU.madot
WHERE (mamau = -1 OR 1 = 1) AND ((DOTHIENMAU.madot = -1 OR 1 = 1) OR (DOTHIENMAU.madot IN (SELECT madot FROM DOTHIENMAU WHERE (YEAR(ngaybatdau) = 2017 OR 1 = 1) AND (MONTH(ngaybatdau) = 1 OR 1 = 1))))

SELECT SUM(soluong) FROM NGUOIHIENMAU JOIN LICHSUHIENMAU ON NGUOIHIENMAU.manguoi = LICHSUHIENMAU.manguoi JOIN DOTHIENMAU ON LICHSUHIENMAU.madot = DOTHIENMAU.madot 
WHERE mamau = 2 AND (DOTHIENMAU.madot IN (SELECT madot FROM DOTHIENMAU WHERE YEAR(ngaybatdau) = 2017))